library(data.table, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(DT, warn.conflicts = FALSE)
library(elastic, warn.conflicts = FALSE)
library(future)
library(future.callr)
library(ggplot2)
library(leaflet)
library(lubridate, warn.conflicts = FALSE)
library(plotly, warn.conflicts = FALSE)
library(promises)
library(shiny)
library(shinydashboard, warn.conflicts = FALSE)
library(shinyjs, warn.conflicts = FALSE)

options(dplyr.summarise.inform = FALSE)

plan(callr)

source('dashboard_utils.R')
source('sentiment_timeline_module.R')
source('sentiment_timeline_likert_module.R')
source('sentiment_likert_module.R')
source('sentiment_module.R')
source('volume_timeline_module.R')
source('sentiment_histogram_module.R')
source('neighbourhood_map_module.R')
source('sentiment_neighbourhoods_module.R')
source('search_results_table_module.R')
source('search_bar_module.R')
source('data_download_module.R')

RESULTS_PER_PAGE = as.numeric(get_configs()$results_per_page)
N_CHAR_NO_MATCH = as.numeric(get_configs()$n_char_no_match)
N_CHAR_HIGHLIGHTS = as.numeric(get_configs()$n_char_highlights)

add_health_check(config)
